import fs from 'node:fs/promises';
import path from 'node:path';
import vm from 'node:vm';
const ROOT=process.cwd(),OUT=path.join(ROOT,'bot-results-v53');
const SYMBOL=process.env.SYMBOL||'BTCUSDT',TFS=(process.env.TIMEFRAMES||'1h,4h,12h,1d').split(','),MAX=+(process.env.MAX_CANDLES||50000),MAXB=+(process.env.MAX_BARS||120),WARM=+(process.env.WARMUP||100);
const BASE='https://data-api.binance.vision/api/v3/klines',sleep=m=>new Promise(r=>setTimeout(r,m)),finite=x=>Number.isFinite(Number(x));
function agg(es){const c=es.filter(e=>e.outcome==='target'||e.outcome==='stop'),w=c.filter(e=>e.outcome==='target'),l=c.filter(e=>e.outcome==='stop');const R=c.map(e=>+e.r).filter(Number.isFinite),gw=w.reduce((s,e)=>s+(+e.r||0),0),gl=Math.abs(l.reduce((s,e)=>s+(+e.r||0),0)),tot=R.reduce((s,x)=>s+x,0);return{samples:es.length,closed:c.length,wins:w.length,losses:l.length,open:es.filter(e=>e.outcome==='open').length,ambiguous:es.filter(e=>e.outcome==='ambiguous').length,winRate:c.length?w.length/c.length:null,totalR:tot,avgR:c.length?tot/c.length:null,profitFactor:gl?gw/gl:null}}
async function page(tf,end){const u=new URL(BASE);u.searchParams.set('symbol',SYMBOL);u.searchParams.set('interval',tf);u.searchParams.set('limit','1000');if(end)u.searchParams.set('endTime',end);for(let a=1;a<=5;a++){try{const r=await fetch(u),t=await r.text();if(r.ok)return JSON.parse(t);if(r.status===429||r.status>=500){await sleep(a*1000);continue}throw Error('Binance HTTP '+r.status)}catch(e){if(a===5)throw e;await sleep(a*1000)}}}
async function data(tf){const ms={'1h':36e5,'4h':144e5,'12h':432e5,'1d':864e5}[tf];let end=Date.now()-ms,all=[];while(all.length<MAX){const p=await page(tf,end);if(!p.length)break;all.push(...p);if(p.length<1000)break;end=+p[0][0]-1;await sleep(80)}const m=new Map();for(const k of all)m.set(+k[0],{time:+k[0],open:+k[1],high:+k[2],low:+k[3],close:+k[4],volume:+k[5]});return{tf,cs:[...m.values()].sort((a,b)=>a.time-b.time).slice(-MAX)}}
async function engine(){const s={console,globalThis:{}};vm.createContext(s);vm.runInContext(await fs.readFile(path.join(ROOT,'src/gannwyck-model1.js'),'utf8'),s);vm.runInContext(await fs.readFile(path.join(ROOT,'src/research-stats.js'),'utf8'),s);return s.globalThis}
const candidates=[
{id:'BASELINE',label:'Sem filtro adicional',ok:()=>true},
{id:'AGE_LE_720',label:'Idade estrutural <=720 barras',ok:e=>finite(e.entryIndex)&&finite(e.t2)&&e.entryIndex-e.t2<=720},
{id:'AGE_GE_721',label:'Idade estrutural >=721 barras',ok:e=>finite(e.entryIndex)&&finite(e.t2)&&e.entryIndex-e.t2>=721},
{id:'RISK_GE_0.5PCT',label:'Risco estrutural >=0,50%',ok:e=>finite(e.entry)&&+e.entry?Math.abs((+e.risk||0)/+e.entry)>=.005:false},
{id:'RANGE_GE_5PCT',label:'Range percentual >=5%',ok:e=>finite(e.rangePctEntry)&&+e.rangePctEntry>=.05},
{id:'BOS_T3_GE_12',label:'BOS->T3 >=12 barras',ok:e=>finite(e.bosTap3Bars)&&+e.bosTap3Bars>=12}
];
function evaluate(events){const ordered=[...events].sort((a,b)=>(+a.entryIndex)-(+b.entryIndex)),closed=ordered.filter(e=>e.outcome==='target'||e.outcome==='stop'),n=closed.length,a=Math.floor(n*.6),b=Math.floor(n*.8);const trainIds=new Set(closed.slice(0,a).map(e=>e.id)),valIds=new Set(closed.slice(a,b).map(e=>e.id)),testIds=new Set(closed.slice(b).map(e=>e.id));const parts={train:ordered.filter(e=>trainIds.has(e.id)),validation:ordered.filter(e=>valIds.has(e.id)),finalOOS:ordered.filter(e=>testIds.has(e.id))};const table=candidates.map(c=>({candidate:c.id,label:c.label,train:agg(parts.train.filter(c.ok)),validation:agg(parts.validation.filter(c.ok)),finalOOS:agg(parts.finalOOS.filter(c.ok))}));const eligible=table.filter(x=>x.train.closed>=8).sort((x,y)=>(Number(y.train.avgR??-Infinity)-Number(x.train.avgR??-Infinity))||(Number(y.train.totalR??-Infinity)-Number(x.train.totalR??-Infinity)));const selected=eligible[0]?.candidate||null;return{split:{closedEvents:n,trainPct:.6,validationPct:.2,finalOOSPct:.2,trainClosed:a,validationClosed:b-a,finalOOSClosed:n-b},candidates:table,selection:{selected,rule:'fixed candidate set; maximize training Avg R with >=8 closed training events; validation and final OOS are not used for selection',chosen:table.find(x=>x.candidate===selected)||null}}}
function run(d,E){const M=E.GannWyckModel1,S=E.GannWyckResearchStats,bt=M.backtestCausal(d.cs,{warmup:WARM,maxBars:MAXB}),rows=bt.events.map(e=>S.featureRow(e,d.cs)),control=evaluate(rows),chosen=control.selection.chosen,final=chosen?.finalOOS||null,audit=M.lookaheadAudit(d.cs,{warmup:WARM,maxBars:MAXB});return{version:'V5.3-CONTROLLED',source:{exchange:'Binance Spot public market data',symbol:SYMBOL,timeframe:d.tf,candles:d.cs.length},rules:{realDataOnly:true,noSyntheticData:true,causal:true,parametersFrozen:true,noOosOptimization:true,selectionUsesTrainingOnly:true,finalHoldoutUntouched:true},backtest:bt.summary,audit:{ok:audit.ok,events:audit.events,violations:audit.violations},control,finalHoldoutGate:{minimumClosed:!!final&&final.closed>=8,positive:!!final&&final.totalR>0,passed:!!final&&final.closed>=8&&final.totalR>0},events:rows}}
(async()=>{await fs.mkdir(OUT,{recursive:true});const E=await engine(),all=[];for(const raw of TFS){const tf=raw.trim(),d=await data(tf),r=run(d,E);all.push(r);await fs.writeFile(path.join(OUT,SYMBOL+'_'+tf+'_V5.3.json'),JSON.stringify(r,null,2));console.log(tf,{selected:r.control.selection.selected,train:r.control.selection.chosen?.train,validation:r.control.selection.chosen?.validation,finalOOS:r.control.selection.chosen?.finalOOS,gate:r.finalHoldoutGate})}const sum={version:'V5.3-CONTROLLED',generatedAt:new Date().toISOString(),symbol:SYMBOL,timeframes:all.map(r=>({timeframe:r.source.timeframe,candles:r.source.candles,audit:r.audit,selection:r.control.selection,finalHoldoutGate:r.finalHoldoutGate})),allFinalHoldoutsPass:all.every(r=>r.finalHoldoutGate.passed)};await fs.writeFile(path.join(OUT,'summary.json'),JSON.stringify(sum,null,2));await fs.writeFile(path.join(OUT,'SUMMARY.md'),'# Controlled V5.3\\n\\n'+all.map(r=>'## '+r.source.timeframe+'\\nSelected: **'+(r.control.selection.selected||'NONE')+'**\\nFinal holdout: **'+(r.finalHoldoutGate.passed?'PASS':'FAIL')+'**').join('\\n\\n'))})().catch(e=>{console.error(e);process.exitCode=1})