const fs=require('fs/promises'),path=require('path'),vm=require('vm');
const ROOT=process.cwd(),OUT=path.join(ROOT,'bot-results');
const SYMBOL=process.env.SYMBOL||'BTCUSDT',TFS=(process.env.TIMEFRAMES||'1h,4h,12h,1d').split(','),MAX=+(process.env.MAX_CANDLES||50000),MAXB=+(process.env.MAX_BARS||120),WARM=+(process.env.WARMUP||100);
const BASE='https://data-api.binance.vision/api/v3/klines',sleep=m=>new Promise(r=>setTimeout(r,m)),finite=x=>Number.isFinite(Number(x));
function agg(es){const c=es.filter(e=>e.outcome==='target'||e.outcome==='stop'),w=c.filter(e=>e.outcome==='target'),l=c.filter(e=>e.outcome==='stop'),R=c.map(e=>+e.r).filter(Number.isFinite),gw=w.reduce((s,e)=>s+(+e.r||0),0),gl=Math.abs(l.reduce((s,e)=>s+(+e.r||0),0)),tot=R.reduce((s,x)=>s+x,0);return{samples:es.length,closed:c.length,wins:w.length,losses:l.length,ambiguous:es.filter(e=>e.outcome==='ambiguous').length,open:es.filter(e=>e.outcome==='open').length,winRate:c.length?w.length/c.length:null,totalR:tot,avgR:c.length?tot/c.length:null,profitFactor:gl?gw/gl:null}};
function rpc(e){return finite(e.entry)&&+e.entry?Math.abs((+e.risk||0)/+e.entry):null}
function age(e){return finite(e.entryIndex)&&finite(e.t2)?+e.entryIndex-+e.t2:null}
async function page(tf,end){const u=new URL(BASE);u.searchParams.set('symbol',SYMBOL);u.searchParams.set('interval',tf);u.searchParams.set('limit','1000');if(end)u.searchParams.set('endTime',end);for(let a=1;a<=5;a++){try{const r=await fetch(u),t=await r.text();if(r.ok)return JSON.parse(t);if(r.status===429||r.status>=500){await sleep(a*1000);continue}throw Error('Binance HTTP '+r.status)}catch(e){if(a===5)throw e;await sleep(a*1000)}}}
async function data(tf){const ms={'1h':36e5,'4h':144e5,'12h':432e5,'1d':864e5}[tf];let end=Date.now()-ms,all=[];while(all.length<MAX){const p=await page(tf,end);if(!p.length)break;all.push(...p);if(p.length<1000)break;end=+p[0][0]-1;await sleep(80)}const m=new Map();for(const k of all)m.set(+k[0],{time:+k[0],open:+k[1],high:+k[2],low:+k[3],close:+k[4],volume:+k[5]});const cs=[...m.values()].sort((a,b)=>a.time-b.time).slice(-MAX);return{tf,cs}}
async function engine(){const s={console,globalThis:{}};vm.createContext(s);vm.runInContext(await fs.readFile(path.join(ROOT,'src/gannwyck-model1.js'),'utf8'),s);vm.runInContext(await fs.readFile(path.join(ROOT,'src/research-stats.js'),'utf8'),s);return s.globalThis}
function run(d,E){const cs=d.cs,M=E.GannWyckModel1,S=E.GannWyckResearchStats,bt=M.backtestCausal(cs,{warmup:WARM,maxBars:MAXB}),audit=M.lookaheadAudit(cs,{warmup:WARM,maxBars:MAXB}),rows=bt.events.map(e=>S.featureRow(e,cs)),closed=rows.filter(e=>e.outcome==='target'||e.outcome==='stop'),oos=rows.filter(e=>new Set(closed.slice(Math.floor(closed.length/2)).map(x=>x.id)).has(e.id)),top=n=>{const ids=new Set([...oos].filter(e=>e.outcome==='target'||e.outcome==='stop').sort((a,b)=>(+b.r)-(+a.r)).slice(0,n).map(e=>e.id));return agg(oos.filter(e=>!ids.has(e.id)))},wf=S.walkForwardDiagnostics(rows,{folds:5,initialFraction:.5}),floors=[.0025,.005,.0075,.01,.015,.02],floor=floors.map(f=>{const k=oos.filter(e=>finite(rpc(e))&&rpc(e)>=f);return{floor:f,eligible:k.length,excluded:oos.length-k.length,...agg(k)}}),ageCaps=[168,720,1440,2880,5760].map(c=>{const k=oos.filter(e=>finite(age(e))&&age(e)<=c);return{maxAgeBars:c,excluded:oos.length-k.length,...agg(k)}}),costs=[0,.05,.1,.2,.3,.5].map(c=>({costR:c,...agg(oos.map(e=>({...e,r:(+e.r)-c})))})),g={lookahead:audit.ok,minOOS:oos.length>=20,oosPositive:(+agg(oos).totalR)>0,top1:(+top(1).totalR)>0,top3:(+top(3).totalR)>0,wfPositive:wf.folds.filter(f=>+f.avgR>0).length>=3};return{version:'V5.2-AUTO',generatedAt:new Date().toISOString(),source:{exchange:'Binance Spot public market data',symbol:SYMBOL,timeframe:d.tf,candles:cs.length},rules:{realDataOnly:true,noSyntheticData:true,causal:true,parametersFrozen:true,noOosOptimization:true,maxBars:MAXB},backtest:bt.summary,audit,oos:agg(oos),stress:{removeTop1:top(1),removeTop2:top(2),removeTop3:top(3),costSensitivity:costs},riskFloorExclusion:floor,ageCapScenarios:ageCaps,walkForward:wf,gate:{...g,passed:Object.values(g).every(Boolean)},events:rows}}
(async()=>{await fs.mkdir(OUT,{recursive:true});const E=await engine(),all=[];for(const tf of TFS){const d=await data(tf.trim());const r=run(d,E);all.push(r);await fs.writeFile(path.join(OUT,SYMBOL+'_'+tf.trim()+'_V5.2.json'),JSON.stringify(r,null,2));console.log(tf,r.gate)}const sum={version:'V5.2-AUTO',generatedAt:new Date().toISOString(),symbol:SYMBOL,timeframes:all.map(r=>({timeframe:r.source.timeframe,candles:r.source.candles,gate:r.gate,oos:r.oos,walkForward:r.walkForward.overall})),allGatesPassed:all.every(r=>r.gate.passed)};await fs.writeFile(path.join(OUT,'summary.json'),JSON.stringify(sum,null,2));await fs.writeFile(path.join(OUT,'SUMMARY.md'),'# Autonomous V5.2\n\n'+all.map(r=>'## '+r.source.timeframe+'\nGate: **'+(r.gate.passed?'PASS':'FAIL')+'**\nOOS Total R: '+r.oos.totalR+'\nWF Total R: '+r.walkForward.overall.totalR).join('\n\n'));if(!sum.allGatesPassed)process.exitCode=2})().catch(e=>{console.error(e);process.exitCode=1})