/* GannWyck Model 1 engine. Experimental, causal and rule-based. */
(function(root){'use strict';
const EPS=1e-12;
const finite=v=>Number.isFinite(Number(v));
function normalizeCandles(candles){return(candles||[]).map((c,i)=>({index:Number.isInteger(c.index)?c.index:i,time:c.time??c.timestamp??i,open:+c.open,high:+c.high,low:+c.low,close:+c.close,volume:finite(c.volume)?+c.volume:null})).filter(c=>[c.open,c.high,c.low,c.close].every(finite));}
function detectTrend(cs,lookback=20){if(cs.length<3)return'unknown';const n=Math.min(lookback,cs.length-1),a=cs[cs.length-1-n].close,b=cs.at(-1).close;if(b>a*1.002)return'up';if(b<a*.998)return'down';return'range';}
function findRange(cs,trend,lookback=80){const s=Math.max(0,cs.length-lookback),a=cs.slice(s);if(!a.length)return null;let hi=a[0],lo=a[0];for(const c of a){if(c.high>hi.high)hi=c;if(c.low<lo.low)lo=c}const rangeHigh=hi.high,rangeLow=lo.low,range=rangeHigh-rangeLow;if(!(range>EPS))return null;return{trend,rangeHigh,rangeLow,range,highIndex:hi.index,lowIndex:lo.index,midpoint:rangeLow+range*.5};}
function calculateDL(r){const R=r.range;return{upper:r.rangeLow+R*1.35,zero:r.rangeLow,lower:r.rangeLow-R*.35,upperFromHigh:r.rangeHigh+R*.35};}
function inDL(p,dl){return p<=dl.upper+EPS&&p>=dl.lower-EPS;}
function inExtreme(p,dl,trend){return trend==='up'?p<=dl.zero+EPS&&p>=dl.lower-EPS:p>=dl.zero-EPS&&p<=dl.upperFromHigh+EPS;}
function findTaps(cs,dl,trend){const candidates=[];for(const c of cs){const price=trend==='up'?c.low:c.high;if(inDL(price,dl))candidates.push({index:c.index,time:c.time,price,type:trend==='up'?'demand':'supply',high:c.high,low:c.low,close:c.close});}if(!candidates.length)return[];const first=candidates[0],after=candidates.filter(t=>t.index>first.index);if(!after.length)return[first];const second=trend==='up'?after.reduce((best,t)=>!best||t.high>best.high?t:best,null):after.reduce((best,t)=>!best||t.low<best.low?t:best,null);return second?[first,second]:[first];}
function detectBosAfter(cs,tap2,trend){if(!tap2)return null;const start=tap2.index+1;if(start>=cs.length)return null;let level=trend==='up'?-Infinity:Infinity;for(let i=0;i<start;i++){if(trend==='up')level=Math.max(level,cs[i].high);else level=Math.min(level,cs[i].low);}for(let i=start;i<cs.length;i++){if(trend==='up'&&cs[i].close>level+EPS)return{index:cs[i].index,type:'bullish',level,close:cs[i].close};if(trend==='down'&&cs[i].close<level-EPS)return{index:cs[i].index,type:'bearish',level,close:cs[i].close};}return null;}
function findTap3After(cs,dl,trend,bosIndex,minDisplacement=2){if(!Number.isInteger(bosIndex))return null;const minBars=Math.max(1,Number.isInteger(minDisplacement)?minDisplacement:2);for(let i=bosIndex+minBars;i<cs.length;i++){const c=cs[i],price=trend==='up'?c.low:c.high;if(inExtreme(price,dl,trend))return{index:c.index,time:c.time,price,type:trend==='up'?'demand':'supply',high:c.high,low:c.low,close:c.close,displacement:i-bosIndex};}return null;}
function buildSignal(cs,r,taps,bos,tap3,trend){if(!r||taps.length<2||!bos||!tap3||tap3.index>=cs.length-1)return null;const entryIndex=tap3.index+1,entry=cs[entryIndex].open,stop=trend==='up'?tap3.low:tap3.high,target=trend==='up'?r.rangeHigh:r.rangeLow,risk=trend==='up'?entry-stop:stop-entry,reward=trend==='up'?target-entry:entry-target;const directional=trend==='up'?target>entry+EPS&&stop<entry-EPS:target<entry-EPS&&stop>entry+EPS;if(!directional||risk<=EPS||reward<=EPS)return null;return{side:trend==='up'?'LONG':'SHORT',entry,stop,target,risk,reward,rr:reward/risk,confirmationIndex:bos.index,tap3Index:tap3.index,entryIndex,entryReason:'next_open_after_tap3',valid:true};}
function findFirstCausalSetup(cs,t2Index,opt={}){const snapshot=cs.slice(0,t2Index+1),trend=detectTrend(snapshot,opt.trendLookback||20);if(trend!=='up'&&trend!=='down')return null;const range=findRange(snapshot,trend,opt.lookback||80);if(!range)return null;const dl=calculateDL(range),taps=findTaps(snapshot,dl,trend);if(taps.length<2||taps[1].index!==t2Index)return null;const tap2=taps[1],bos=detectBosAfter(cs,tap2,trend);if(!bos)return null;const tap3=findTap3After(cs,dl,trend,bos.index,opt.minTap3Displacement??2);if(!tap3)return null;const signal=buildSignal(cs,range,taps,bos,tap3,trend);if(!signal)return null;return{trend,range,dl,taps,bos,tap3,signal};}
function analyzeCausal(input,opt={}){const cs=normalizeCandles(input);for(let i=Math.max(20,opt.warmup||100);i<cs.length-1;i++){const candidate=findFirstCausalSetup(cs,i,opt);if(candidate)return{ok:true,model:'GannWyck Model 1',experimental:true,causal:true,...candidate,rules:{tapsRequired:3,bosBeforeTap3:true,bosConfirmedByClose:true,target:'range snapshot frozen at T2',stop:'Tap 3 candle extreme',entry:'next candle open after Tap 3',dlFib:[1.35,0,-.35],minTap3Displacement:opt.minTap3Displacement??2}};}return{ok:true,model:'GannWyck Model 1',experimental:true,causal:true,signal:null,rejection:'no_complete_causal_setup'};}
function outcome(cs,signal,maxBars=120){if(!signal||!signal.valid)return{status:'invalid',bars:0,r:0};const start=signal.entryIndex;for(let i=start;i<Math.min(cs.length,start+maxBars);i++){const c=cs[i];if(signal.side==='LONG'){const hitStop=c.low<=signal.stop,hitTarget=c.high>=signal.target;if(hitStop&&hitTarget)return{status:'ambiguous',index:i,time:c.time,bars:i-start,r:null};if(hitStop)return{status:'stop',index:i,time:c.time,bars:i-start,r:-1};if(hitTarget)return{status:'target',index:i,time:c.time,bars:i-start,r:signal.rr};}else{const hitStop=c.high>=signal.stop,hitTarget=c.low<=signal.target;if(hitStop&&hitTarget)return{status:'ambiguous',index:i,time:c.time,bars:i-start,r:null};if(hitStop)return{status:'stop',index:i,time:c.time,bars:i-start,r:-1};if(hitTarget)return{status:'target',index:i,time:c.time,bars:i-start,r:signal.rr};}}return{status:'open',bars:Math.max(0,Math.min(cs.length,start+maxBars)-start),r:0};}
function backtestCausal(input,opt={}){const cs=normalizeCandles(input),warmup=Math.max(20,opt.warmup||100),events=[],seen=new Set();for(let t2=warmup;t2<cs.length-1;t2++){const setup=findFirstCausalSetup(cs,t2,opt);if(!setup||setup.taps[1].index!==t2)continue;const s=setup.signal,key=[s.entryIndex,s.side].join(':');if(seen.has(key))continue;seen.add(key);const o=outcome(cs,s,opt.maxBars||120),t1=setup.taps[0],t2c=setup.taps[1],t3=setup.tap3,range=setup.range;events.push({id:events.length+1,time:cs[s.entryIndex]?.time,setupTime:cs[s.confirmationIndex]?.time,side:s.side,entry:s.entry,stop:s.stop,target:s.target,risk:s.risk,reward:s.reward,rr:s.rr,r:o.r,t1:t1.index,t2:t2c.index,bos:setup.bos.index,t3:t3.index,confirmationIndex:s.confirmationIndex,entryIndex:s.entryIndex,rangeHigh:range.rangeHigh,rangeLow:range.rangeLow,rangeSize:range.range,t1ToT2:t2c.index-t1.index,t2ToBOS:setup.bos.index-t2c.index,bosToT3:t3.index-setup.bos.index,bosLevel:setup.bos.level,bosDistance:Math.abs(s.entry-setup.bos.level),outcome:o.status,outcomeIndex:o.index??null,bars:o.bars,causal:true});}
const closed=events.filter(e=>e.outcome==='target'||e.outcome==='stop'),wins=closed.filter(e=>e.outcome==='target'),losses=closed.filter(e=>e.outcome==='stop'),ambiguous=events.filter(e=>e.outcome==='ambiguous'),totalR=closed.reduce((a,e)=>a+e.r,0),grossWinR=wins.reduce((a,e)=>a+e.r,0),grossLossR=Math.abs(losses.reduce((a,e)=>a+e.r,0));return{ok:true,model:'GannWyck Model 1',experimental:true,causal:true,candlesCount:cs.length,events,summary:{signals:events.length,closed:closed.length,target:wins.length,stop:losses.length,open:events.filter(e=>e.outcome==='open').length,ambiguous:ambiguous.length,winRate:closed.length?wins.length/closed.length:null,totalR,avgR:closed.length?totalR/closed.length:null,avgWinR:wins.length?grossWinR/wins.length:null,avgLossR:losses.length?grossLossR/losses.length:null,expectancyR:closed.length?totalR/closed.length:null,profitFactor:grossLossR?grossWinR/grossLossR:null}};}
function same(a,b){const n=(x)=>Number.isFinite(Number(x))?Number(x):null;return a.side===b.side&&a.t1===b.t1&&a.t2===b.t2&&a.bos===b.bos&&a.t3===b.t3&&a.entryIndex===b.entryIndex&&Math.abs(n(a.entry)-n(b.entry))<1e-9&&Math.abs(n(a.stop)-n(b.stop))<1e-9&&Math.abs(n(a.target)-n(b.target))<1e-9;}
function lookaheadAudit(input,opt={}){const cs=normalizeCandles(input),bt=backtestCausal(cs,opt),violations=[];for(const e of bt.events){const replay=findFirstCausalSetup(cs,e.t2,opt);if(!replay||!same(e,{...replay.signal,t1:replay.taps[0].index,t2:replay.taps[1].index,bos:replay.bos.index,t3:replay.tap3.index}))violations.push({eventId:e.id,t2:e.t2,entryIndex:e.entryIndex,reason:'event_not_reproducible_from_data_available_at_T2'});}return{ok:violations.length===0,eventsChecked:bt.events.length,violations,method:'setup is frozen from candles through T2; BOS/T3/entry are searched only forward from that snapshot'};}
function backtest(input,opt={}){return backtestCausal(input,opt);}
root.GannWyckModel1={analyze:analyzeCausal,analyzeCausal,backtest,backtestCausal,outcome,normalizeCandles,detectTrend,findRange,calculateDL,findTaps,detectBosAfter,findTap3After,lookaheadAudit};
})(typeof window!=='undefined'?window:globalThis);