/* GannWyck Model 1 engine. Experimental and rule-based. */
(function(root){'use strict';
const EPS=1e-12;
const finite=v=>Number.isFinite(Number(v));
function normalizeCandles(candles){return(candles||[]).map((c,i)=>({index:Number.isInteger(c.index)?c.index:i,time:c.time??c.timestamp??i,open:+c.open,high:+c.high,low:+c.low,close:+c.close,volume:finite(c.volume)?+c.volume:null})).filter(c=>[c.open,c.high,c.low,c.close].every(finite));}
function detectTrend(cs,lookback=20){if(cs.length<3)return'unknown';const n=Math.min(lookback,cs.length-1),a=cs[cs.length-1-n].close,b=cs.at(-1).close;if(b>a*1.002)return'up';if(b<a*.998)return'down';return'range';}
function findRange(cs,trend,lookback=80){const s=Math.max(0,cs.length-lookback),a=cs.slice(s);if(!a.length)return null;let hi=a[0],lo=a[0];for(const c of a){if(c.high>hi.high)hi=c;if(c.low<lo.low)lo=c}const rangeHigh=hi.high,rangeLow=lo.low,range=rangeHigh-rangeLow;if(!(range>EPS))return null;return{trend,rangeHigh,rangeLow,range,highIndex:hi.index,lowIndex:lo.index,midpoint:rangeLow+range*.5};}
function calculateDL(r){const R=r.range;return{upper:r.rangeLow+R*1.35,zero:r.rangeLow,lower:r.rangeLow-R*.35,upperFromHigh:r.rangeHigh+R*.35};}
function inDL(p,dl){return p<=dl.upper+EPS&&p>=dl.lower-EPS;}
function findTaps(cs,dl,trend){const candidates=[];for(const c of cs){const price=trend==='up'?c.low:c.high;if(inDL(price,dl))candidates.push({index:c.index,time:c.time,price,type:trend==='up'?'demand':'supply',high:c.high,low:c.low,close:c.close});}if(!candidates.length)return[];const first=candidates[0];const second=candidates.slice(1).reduce((best,t)=>!best?t:(trend==='up'?(t.price<best.price?t:best):(t.price>best.price?t:best)),null);const taps=[first];if(second&&second.index!==first.index)taps.push(second);return taps;}
function findTap3(cs,dl,trend,bosIndex,minDisplacement=2){if(!Number.isInteger(bosIndex))return null;const minBars=Math.max(1,Number.isInteger(minDisplacement)?minDisplacement:2);for(let i=bosIndex+minBars;i<cs.length;i++){const c=cs[i],price=trend==='up'?c.low:c.high;if(inDL(price,dl))return{index:c.index,time:c.time,price,type:trend==='up'?'demand':'supply',high:c.high,low:c.low,close:c.close,displacement:i-bosIndex};}return null;}
function detectBOS(cs,tap2,trend){if(!tap2)return null;const start=tap2.index+1;if(start>=cs.length)return null;if(trend==='up'){let level=-Infinity;for(let i=0;i<start;i++)level=Math.max(level,cs[i].high);for(let i=start;i<cs.length;i++)if(cs[i].close>level+EPS)return{index:i,type:'bullish',level,close:cs[i].close};}if(trend==='down'){let level=Infinity;for(let i=0;i<start;i++)level=Math.min(level,cs[i].low);for(let i=start;i<cs.length;i++)if(cs[i].close<level-EPS)return{index:i,type:'bearish',level,close:cs[i].close};}return null;}
function buildSignal(cs,r,taps,bos,tap3,trend){if(!r||taps.length<2||!bos||!tap3||bos.index>=tap3.index||tap3.index>=cs.length)return null;const entry=cs[bos.index].close,stop=tap3.price,target=trend==='up'?r.rangeHigh:r.rangeLow,risk=trend==='up'?entry-stop:stop-entry,reward=trend==='up'?target-entry:entry-target;const directional=trend==='up'?target>entry+EPS&&stop<entry-EPS:target<entry-EPS&&stop>entry+EPS;if(!directional||risk<=EPS||reward<=EPS)return null;return{side:trend==='up'?'LONG':'SHORT',entry,stop,target,risk,reward,rr:reward/risk,confirmationIndex:bos.index,tap3Index:tap3.index,valid:true};}
function analyze(input,opt={}){const candles=normalizeCandles(input),lookback=opt.lookback||80,trend=opt.trend||detectTrend(candles,opt.trendLookback||20),range=findRange(candles,trend,lookback);if(!range)return{ok:false,reason:'range_not_found',candlesCount:candles.length};const dl=calculateDL(range),taps=findTaps(candles,dl,trend),tap2=taps[1]||null,bos=detectBOS(candles,tap2,trend),tap3=findTap3(candles,dl,trend,bos?.index,opt.minTap3Displacement??2),signal=buildSignal(candles,range,taps,bos,tap3,trend);let rejection=null;if(bos&&!tap3)rejection='tap3_not_confirmed_after_bos';else if(bos&&tap3&&trend==='up'&&!(range.rangeHigh>candles[bos.index].close+EPS))rejection='long_target_not_above_entry';else if(bos&&tap3&&trend==='down'&&!(range.rangeLow<candles[bos.index].close-EPS))rejection='short_target_not_below_entry';return{ok:true,model:'GannWyck Model 1',experimental:true,trend,range,dl,taps:tap3?[...taps,tap3]:taps,bos,signal,rejection,extremeZone:tap2?{type:trend==='up'?'Extreme Demand':'Extreme Supply',price:tap2.price,index:tap2.index}:null,rules:{tapsRequired:3,bosBeforeTap3:true,bosConfirmedByClose:true,target:trend==='down'?'Range Low':'Range High',stop:'Tap 3',entry:'BOS close',directionalTarget:true,dlFib:[1.35,0,-.35],minTap3Displacement:opt.minTap3Displacement??2}};}
function outcome(cs,signal,maxBars=120){if(!signal||!signal.valid)return{status:'invalid',bars:0,r:0};const start=signal.confirmationIndex+1;for(let i=start;i<Math.min(cs.length,start+maxBars);i++){const c=cs[i];if(signal.side==='LONG'){if(c.low<=signal.stop)return{status:'stop',index:i,time:c.time,bars:i-start,r:-1};if(c.high>=signal.target)return{status:'target',index:i,time:c.time,bars:i-start,r:signal.rr};}else{if(c.high>=signal.stop)return{status:'stop',index:i,time:c.time,bars:i-start,r:-1};if(c.low<=signal.target)return{status:'target',index:i,time:c.time,bars:i-start,r:signal.rr};}}return{status:'open',bars:Math.max(0,Math.min(cs.length,start+maxBars)-start),r:0};}
function backtest(input,opt={}){const cs=normalizeCandles(input),warmup=Math.max(20,opt.warmup||100),step=Math.max(1,opt.step||1),events=[],seen=new Set();for(let end=warmup;end<=cs.length;end+=step){const sample=cs.slice(0,end),r=analyze(sample,opt);if(!r.signal?.valid)continue;const key=[r.signal.confirmationIndex,r.signal.side].join(':');if(seen.has(key))continue;seen.add(key);const s=r.signal,o=outcome(cs,s,opt.maxBars||120),t1=r.taps[0],t2=r.taps[1],t3=r.taps[2],range=r.range;events.push({id:events.length+1,time:cs[s.confirmationIndex]?.time,side:s.side,entry:s.entry,stop:s.stop,target:s.target,risk:s.risk,reward:s.reward,rr:s.rr,r:o.r,t1:t1?.index??null,t2:t2?.index??null,bos:r.bos?.index??null,t3:t3?.index??null,rangeHigh:range.rangeHigh,rangeLow:range.rangeLow,rangeSize:range.range,t1ToT2:t1&&t2?t2.index-t1.index:null,t2ToBOS:t2&&r.bos?r.bos.index-t2.index:null,bosToT3:r.bos&&t3?t3.index-r.bos.index:null,bosLevel:r.bos?.level??null,bosDistance:r.bos?Math.abs(s.entry-r.bos.level):null,outcome:o.status,outcomeIndex:o.index??null,bars:o.bars});}const closed=events.filter(e=>e.outcome==='target'||e.outcome==='stop'),wins=closed.filter(e=>e.outcome==='target'),losses=closed.filter(e=>e.outcome==='stop'),totalR=closed.reduce((a,e)=>a+e.r,0),grossWinR=wins.reduce((a,e)=>a+e.r,0),grossLossR=Math.abs(losses.reduce((a,e)=>a+e.r,0));return{ok:true,model:'GannWyck Model 1',experimental:true,candlesCount:cs.length,events,summary:{signals:events.length,closed:closed.length,target:wins.length,stop:losses.length,open:events.filter(e=>e.outcome==='open').length,winRate:closed.length?wins.length/closed.length:null,totalR,avgR:closed.length?totalR/closed.length:null,avgWinR:wins.length?grossWinR/wins.length:null,avgLossR:losses.length?grossLossR/losses.length:null,expectancyR:closed.length?totalR/closed.length:null,profitFactor:grossLossR?grossWinR/grossLossR:null}};}
root.GannWyckModel1={analyze,backtest,outcome,normalizeCandles,detectTrend,findRange,calculateDL,findTaps,findTap3,detectBOS};
})(typeof window!=='undefined'?window:globalThis);