/* GannWyck Model 1 research statistics. Experimental. */
(function(root){'use strict';
function finite(v){return Number.isFinite(Number(v));}
function rMultiple(e){if(!e||!finite(e.entry)||!finite(e.stop)||!finite(e.target))return null;const risk=Math.abs(e.entry-e.stop);if(!(risk>0))return null;return(e.side==='LONG'?e.target-e.entry:e.entry-e.target)/risk;}
function featureRow(e,candles){const t1=finite(e.tap1)?+e.tap1:null,t2=finite(e.tap2)?+e.tap2:null,t3=finite(e.tap3)?+e.tap3:null,bos=finite(e.bos)?+e.bos:null;const c=candles?.[e.confirmationIndex];const rangeSize=finite(e.rangeSize)?+e.rangeSize:null;const rangeLow=finite(e.rangeLow)?+e.rangeLow:null;const rangePct=rangeSize!==null&&rangeLow!==null&&rangeLow!==0?rangeSize/Math.abs(rangeLow):null;const bosDistance=finite(e.bosDistance)?+e.bosDistance:(finite(e.entry)&&finite(e.bosLevel)?Math.abs(+e.entry-+e.bosLevel):null);return{...e,confirmationIndex:e.confirmationIndex??bos,timestamp:e.time??c?.time??null,tap12Bars:t1!==null&&t2!==null?t2-t1:null,tap23Bars:t2!==null&&t3!==null?t3-t2:null,tap2BosBars:t2!==null&&bos!==null?bos-t2:null,bosTap3Bars:bos!==null&&t3!==null?t3-bos:null,realizedR:e.outcome==='target'?rMultiple(e):e.outcome==='stop'?-1:null,normalizedRisk:finite(e.entry)&&finite(e.stop)&&+e.entry!==0?Math.abs(+e.entry-+e.stop)/Math.abs(+e.entry):null,rangePct,bosDistance,bosDistancePct:rangeSize>0&&bosDistance!==null?bosDistance/rangeSize:null,confirmationClose:c?.close??null};}
function group(rows,keyFn){const m=new Map();for(const r of rows){const k=keyFn(r);if(!m.has(k))m.set(k,[]);m.get(k).push(r)}return m;}
function aggregate(rows){const closed=rows.filter(r=>r.outcome==='target'||r.outcome==='stop'),wins=closed.filter(r=>r.outcome==='target'),losses=closed.filter(r=>r.outcome==='stop'),rs=closed.map(r=>r.realizedR).filter(finite),grossWin= wins.reduce((a,r)=>a+(finite(r.realizedR)?r.realizedR:0),0),grossLoss=Math.abs(losses.reduce((a,r)=>a+(finite(r.realizedR)?r.realizedR:0),0));return{samples:rows.length,closed:closed.length,wins:wins.length,losses:losses.length,open:rows.length-closed.length,winRate:closed.length?wins.length/closed.length:null,avgR:rs.length?rs.reduce((a,b)=>a+b,0)/rs.length:null,medianR:rs.length?[...rs].sort((a,b)=>a-b)[Math.floor(rs.length/2)]:null,profitFactor:grossLoss>0?grossWin/grossLoss:null};}
function bucketNumeric(v,bounds,decimals=0){if(!finite(v))return'unknown';for(let i=1;i<bounds.length;i++)if(v<=bounds[i])return `${bounds[i-1]}-${bounds[i]}`;return `${bounds.at(-1)}+`;}
function discoveryBuckets(rows){const spacing=[0,2,4,8,12,20,40],rr=[0,1,2,3],t12=[0,2,5,10,20],t2b=[0,2,5,10,20],bt3=[0,2,4,8,12],range=[0,.01,.025,.05,.1];const make=(field,bounds,name)=>[...group(rows,r=>bucketNumeric(r[field],bounds)).entries()].map(([key,v])=>({bucket:key,group:name,...aggregate(v)}));return{byTapSpacing:make('tap23Bars',spacing,'T2→T3'),byRR:make('rr',rr,'R:R'),byTap12:make('tap12Bars',t12,'T1→T2'),byTap2BOS:make('tap2BosBars',t2b,'T2→BOS'),byBOSTap3:make('bosTap3Bars',bt3,'BOS→T3'),byRangePct:make('rangePct',range,'Range %')};}
function rankPatterns(discovery,opt={}){const minSamples=Math.max(1,Number(opt.minSamples??10));const groups=[];for(const [dimension,rows] of Object.entries(discovery||{})){if(!Array.isArray(rows))continue;for(const r of rows)if(r.bucket!=='unknown'&&r.samples>=minSamples)groups.push({...r,dimension,score:finite(r.avgR)?r.avgR:-Infinity});}return groups.sort((a,b)=>b.score-a.score||b.samples-a.samples);}
function discover(input,opt={}){const base=input?.events||input?.rows||[];const candles=input?.candles||[];const rows=base.map(e=>featureRow(e,candles));const bySide=[...group(rows,r=>r.side??'unknown')].map(([key,v])=>({group:key,...aggregate(v)}));const out=aggregate(rows),b=discoveryBuckets(rows);const ranking=rankPatterns(b,opt);return{ok:true,experimental:true,model:'GannWyck Model 1',rows,summary:out,bySide,byTapSpacing:b.byTapSpacing,byRR:b.byRR,byTap12:b.byTap12,byTap2BOS:b.byTap2BOS,byBOSTap3:b.byBOSTap3,byRangePct:b.byRangePct,ranking,minSamples:Math.max(1,Number(opt.minSamples??10))};}
function fromBacktests(results,opt={}){const rows=[];for(const x of results||[])for(const e of x?.events||[])rows.push({...e,time:e.time,symbol:x.symbol??null,timeframe:x.timeframe??null});return discover({rows},opt);}
root.GannWyckResearchStats={discover,fromBacktests,aggregate,featureRow,rankPatterns};
})(typeof window!=='undefined'?window:globalThis);