/* GannWyck Model 1 research statistics. Experimental. */
(function(root){'use strict';
function finite(v){return Number.isFinite(Number(v));}
function rMultiple(e){if(!e||!finite(e.entry)||!finite(e.stop)||!finite(e.target))return null;const risk=Math.abs(e.entry-e.stop);if(!(risk>0))return null;return(e.side==='LONG'?e.target-e.entry:e.entry-e.target)/risk;}
function erf(x){const s=x<0?-1:1,a=Math.abs(x),t=1/(1+0.3275911*a),y=1-((((1.061405429*t-1.453152027)*t+1.421413741)*t-0.284496736)*t+0.254829592)*t*Math.exp(-a*a);return s*y;}function normalCdf(x){return 0.5*(1+erf(x/Math.sqrt(2)));}
function wilson(wins,n,z=1.96){if(!(n>0))return{low:null,high:null};const p=wins/n,d=1+z*z/n,c=p+z*z/(2*n),m=z*Math.sqrt((p*(1-p)+z*z/(4*n))/n);return{low:(c-m)/d,high:(c+m)/d};}
function featureRow(e,candles){const t1=finite(e.tap1)?+e.tap1:(finite(e.t1)?+e.t1:null),t2=finite(e.tap2)?+e.tap2:(finite(e.t2)?+e.t2:null),t3=finite(e.tap3)?+e.tap3:(finite(e.t3)?+e.t3:null),bos=finite(e.bos)?+e.bos:null,c=candles?.[e.confirmationIndex],rangeSize=finite(e.rangeSize)?+e.rangeSize:null,rangeLow=finite(e.rangeLow)?+e.rangeLow:null,rangePct=rangeSize!==null&&rangeLow!==null&&rangeLow!==0?rangeSize/Math.abs(rangeLow):null,bosDistance=finite(e.bosDistance)?+e.bosDistance:(finite(e.entry)&&finite(e.bosLevel)?Math.abs(+e.entry-+e.bosLevel):null);return{...e,tap1:t1,tap2:t2,tap3:t3,bos,confirmationIndex:e.confirmationIndex??bos,timestamp:e.time??c?.time??null,tap12Bars:t1!==null&&t2!==null?t2-t1:null,tap23Bars:t2!==null&&t3!==null?t3-t2:null,tap2BosBars:t2!==null&&bos!==null?bos-t2:null,bosTap3Bars:bos!==null&&t3!==null?t3-bos:null,realizedR:e.outcome==='target'?(finite(e.r)?+e.r:rMultiple(e)):e.outcome==='stop'?-1:null,normalizedRisk:finite(e.entry)&&finite(e.stop)&&+e.entry!==0?Math.abs(+e.entry-+e.stop)/Math.abs(+e.entry):null,rangePct,bosDistance,bosDistancePct:rangeSize>0&&bosDistance!==null?bosDistance/rangeSize:null,confirmationClose:c?.close??null};}
function group(rows,keyFn){const m=new Map();for(const r of rows){const k=keyFn(r);if(!m.has(k))m.set(k,[]);m.get(k).push(r)}return m;}
function aggregate(rows,baselineWinRate=null){const closed=rows.filter(r=>r.outcome==='target'||r.outcome==='stop'),wins=closed.filter(r=>r.outcome==='target'),losses=closed.filter(r=>r.outcome==='stop'),rs=closed.map(r=>r.realizedR).filter(finite),grossWin=wins.reduce((a,r)=>a+(finite(r.realizedR)?r.realizedR:0),0),grossLoss=Math.abs(losses.reduce((a,r)=>a+(finite(r.realizedR)?r.realizedR:0),0)),avgR=rs.length?rs.reduce((a,b)=>a+b,0)/rs.length:null,sd=rs.length>1?Math.sqrt(rs.reduce((a,x)=>a+(x-avgR)**2,0)/(rs.length-1)):null,se=sd!==null?sd/Math.sqrt(rs.length):null,z=se&&se>0?avgR/se:null,pPositive=z!==null?1-normalCdf(z):null,ci=wilson(wins.length,closed.length);return{samples:rows.length,closed:closed.length,wins:wins.length,losses:losses.length,open:rows.length-closed.length,winRate:closed.length?wins.length/closed.length:null,winRateLow:ci.low,winRateHigh:ci.high,avgR,medianR:rs.length?[...rs].sort((a,b)=>a-b)[Math.floor((rs.length-1)/2)]:null,profitFactor:grossLoss>0?grossWin/grossLoss:null,expectancyR:avgR,meanRSE:se,meanRZ:z,pValuePositiveExpectancy:pPositive,expectancyScreen:closed.length>=30&&pPositive!==null&&pPositive<0.05?'POSITIVE_SCREEN':'INSUFFICIENT_OR_NOT_SIGNIFICANT',winRateLift:baselineWinRate!==null&&closed.length?wins.length/closed.length-baselineWinRate:null};}
function bucketNumeric(v,bounds){if(!finite(v))return'unknown';for(let i=1;i<bounds.length;i++)if(v<=bounds[i])return String(bounds[i-1])+'-'+String(bounds[i]);return String(bounds.at(-1))+'+';}
function discoveryBuckets(rows){const spacing=[0,2,4,8,12,20,40],rr=[0,1,2,3],t12=[0,2,5,10,20],t2b=[0,2,5,10,20],bt3=[0,2,4,8,12],range=[0,.01,.025,.05,.1];const make=(field,bounds,name)=>[...group(rows,r=>bucketNumeric(r[field],bounds)).entries()].map(([key,v])=>({bucket:key,group:name,...aggregate(v)}));return{byTapSpacing:make('tap23Bars',spacing,'T2→T3'),byRR:make('rr',rr,'R:R'),byTap12:make('tap12Bars',t12,'T1→T2'),byTap2BOS:make('tap2BosBars',t2b,'T2→BOS'),byBOSTap3:make('bosTap3Bars',bt3,'BOS→T3'),byRangePct:make('rangePct',range,'Range %')};}
function rankPatterns(discovery,opt={}){const minSamples=Math.max(1,Number(opt.minSamples??10));const groups=[];for(const [dimension,rows] of Object.entries(discovery||{})){if(!Array.isArray(rows))continue;for(const r of rows)if(r.bucket!=='unknown'&&r.samples>=minSamples)groups.push({...r,dimension,score:finite(r.avgR)?r.avgR:-Infinity});}return groups.sort((a,b)=>b.score-a.score||b.samples-a.samples);}
function discover(input,opt={}){const base=input?.events||input?.rows||[],candles=input?.candles||[],rows=base.map(e=>featureRow(e,candles)),overall=aggregate(rows),baseline=overall.winRate,bySide=[...group(rows,r=>r.side??'unknown')].map(([key,v])=>({group:key,...aggregate(v,baseline)})),b=discoveryBuckets(rows),ranking=rankPatterns(b,opt);return{ok:true,experimental:true,model:'GannWyck Model 1',rows,summary:overall,bySide,byTapSpacing:b.byTapSpacing,byRR:b.byRR,byTap12:b.byTap12,byTap2BOS:b.byTap2BOS,byBOSTap3:b.byBOSTap3,byRangePct:b.byRangePct,ranking,minSamples:Math.max(1,Number(opt.minSamples??10)),statisticsNote:'Expectancy significance is a screening statistic only; buckets are exploratory and must be validated OOS.'};}
function fromBacktests(results,opt={}){const rows=[];for(const x of results||[])for(const e of x?.events||[])rows.push({...e,time:e.time,symbol:x.symbol??null,timeframe:x.timeframe??null});return discover({rows},opt);}
root.GannWyckResearchStats={discover,fromBacktests,aggregate,featureRow,rankPatterns};
})(typeof window!=='undefined'?window:globalThis);